### ISSUE TITLE
Doesn’t work

### ISSUE THREAD

**Issue by Lyneloflight** [MazeWave/Vanilla-Raytraced-Addons-Mirror#1]

**Comment by Lyneloflight** [comment]
When I open it, I get a message saying that it failed to import.

**Comment by MazeWave** [comment]
> When I open it, I get a message saying that it failed to import.

It may be because al my resources packs are not updated to 1.19...
Unfortunately the latest version available for is 1.16

This might be why it doesn't import the resources pack.
